import type {
  Application,
  CreatorProfile,
  CreatorRequest,
  Order,
  Portfolio,
  Review,
  Service,
} from "./types";

const img = (seed: string, w = 800, h = 1000) =>
  `https://picsum.photos/seed/aigao-${seed}/${w}/${h}`;

export const CATEGORIES = [
  { slug: "product", label: "AI 商品场景图" },
  { slug: "portrait", label: "AI 人物写真" },
  { slug: "brand-film", label: "品牌 AI 短片" },
  { slug: "ip", label: "潮玩 IP 动态" },
  { slug: "poster", label: "海报 / KV" },
  { slug: "space", label: "空间与建筑" },
  { slug: "illustration", label: "插画与概念" },
  { slug: "ecom-video", label: "电商短视频" },
];

export const USAGES = ["电商详情页", "品牌传播", "社交媒体", "广告投放", "线下物料", "内部提案"];

export const creators: CreatorProfile[] = [
  {
    id: "c1",
    user_id: "u1",
    handle: "mori-ai-studio",
    display_name: "Mori AI Studio",
    avatar_url: img("mori-avatar", 300, 300),
    cover_url: img("mori-cover", 1600, 600),
    tagline: "商业级 AI 商品视觉 / 品牌短片",
    bio: "专注电商与品牌方向的 AI 视觉制作，六年商业摄影与后期经验转型 AI 工作流。擅长产品质感还原、光影控制与系列一致性，交付前均经过人工精修，可提供源文件与商用授权。",
    verified: true,
    specialties: ["AI 商品场景图", "品牌 AI 短片", "系列一致性"],
    tools: ["Midjourney", "Stable Diffusion", "ComfyUI", "Runway", "Photoshop"],
    workflow: [
      "沟通需求与参考，确认画面方向与风格基调",
      "出 3 组风格草图，需求方确认方向",
      "批量生成 + 人工精修，控制产品结构与光影",
      "输出成片与源文件，附商用授权说明",
    ],
    rating: 4.9,
    reviews_count: 218,
    completed_orders: 342,
    on_time_rate: 98,
    response_minutes: 22,
    price_from: 299,
    city: "上海",
    joined_at: "2024-03",
  },
  {
    id: "c2",
    user_id: "u2",
    handle: "linshan",
    display_name: "林山 Linshan",
    avatar_url: img("linshan-avatar", 300, 300),
    cover_url: img("linshan-cover", 1600, 600),
    tagline: "AI 人物写真 / 时尚大片",
    bio: "时尚方向 AI 创作者，擅长人物面部一致性、服装质感与胶片色调，为多家服饰品牌提供过模特替代方案。",
    verified: true,
    specialties: ["AI 人物写真", "服饰模特", "胶片色调"],
    tools: ["Midjourney", "Flux", "ComfyUI", "Lightroom"],
    workflow: ["确认人物设定与风格", "训练角色一致性", "批量出片", "精修交付"],
    rating: 4.8,
    reviews_count: 156,
    completed_orders: 201,
    on_time_rate: 96,
    response_minutes: 35,
    price_from: 399,
    city: "杭州",
    joined_at: "2024-06",
  },
  {
    id: "c3",
    user_id: "u3",
    handle: "pixel-hu",
    display_name: "胡同学 Pixel",
    avatar_url: img("pixel-avatar", 300, 300),
    cover_url: img("pixel-cover", 1600, 600),
    tagline: "潮玩 IP 动态 / 三维质感",
    bio: "潮玩与 IP 方向创作者，把静态手办转成有呼吸感的动态短片，适合新品预热与社媒投放。",
    verified: false,
    specialties: ["潮玩 IP 动态", "三维质感", "循环动画"],
    tools: ["Midjourney", "Runway", "Kling", "After Effects"],
    workflow: ["IP 形象梳理", "分镜与关键帧", "动态生成与合成", "调色输出"],
    rating: 4.7,
    reviews_count: 88,
    completed_orders: 126,
    on_time_rate: 94,
    response_minutes: 48,
    price_from: 699,
    city: "成都",
    joined_at: "2024-09",
  },
  {
    id: "c4",
    user_id: "u4",
    handle: "studio-north",
    display_name: "北向工作室",
    avatar_url: img("north-avatar", 300, 300),
    cover_url: img("north-cover", 1600, 600),
    tagline: "品牌 KV / 空间视觉",
    bio: "以品牌调性为核心的 AI 视觉团队，承接 KV、海报、空间概念图，风格克制、排版精准。",
    verified: true,
    specialties: ["海报 / KV", "空间与建筑", "品牌传播"],
    tools: ["Midjourney", "Flux", "Figma", "Photoshop"],
    workflow: ["品牌调性拆解", "概念方向提案", "视觉落地", "物料尺寸适配"],
    rating: 4.9,
    reviews_count: 132,
    completed_orders: 178,
    on_time_rate: 99,
    response_minutes: 18,
    price_from: 599,
    city: "北京",
    joined_at: "2023-12",
  },
];

export const services: Service[] = [
  {
    id: "s1",
    creator_id: "c1",
    title: "AI 商品场景图 · 电商主图与详情页整套",
    category: "AI 商品场景图",
    usage: ["电商详情页", "社交媒体"],
    cover_url: img("svc-1", 900, 1100),
    gallery: [img("svc-1a", 900, 700), img("svc-1b", 900, 700), img("svc-1c", 900, 700)],
    price_from: 299,
    delivery_days: 3,
    quantity: "5 张成片",
    revisions: 1,
    commercial_use: true,
    source_files: true,
    media_type: "image",
    description:
      "为电商商品定制 AI 场景图，保证产品结构与材质还原，交付含主图、细节图与氛围图。适配天猫、京东、小红书等平台尺寸。",
    process: [
      { title: "需求确认", detail: "提供产品图与参考，确认风格与使用场景" },
      { title: "风格提案", detail: "24 小时内给出 3 组方向草图" },
      { title: "批量制作", detail: "生成 + 人工精修，控制产品一致性" },
      { title: "交付验收", detail: "输出高清成片与源文件，含 1 次修改" },
    ],
    before_after: {
      before: img("ba-before", 800, 800),
      after: img("ba-after", 800, 800),
      note: "原始白底产品图 → AI 场景重构",
    },
    orders_count: 412,
    rating: 4.9,
  },
  {
    id: "s2",
    creator_id: "c2",
    title: "AI 人物写真 · 品牌模特与个人形象",
    category: "AI 人物写真",
    usage: ["品牌传播", "社交媒体"],
    cover_url: img("svc-2", 900, 1100),
    gallery: [img("svc-2a", 900, 700), img("svc-2b", 900, 700)],
    price_from: 399,
    delivery_days: 4,
    quantity: "8 张成片",
    revisions: 2,
    commercial_use: true,
    source_files: false,
    media_type: "image",
    description:
      "面向服饰、美妆品牌的 AI 人物写真，支持指定人物形象的一致性生成，可用于详情页、社媒与广告素材。",
    process: [
      { title: "形象设定", detail: "确认人物年龄、气质、服装与场景" },
      { title: "一致性训练", detail: "建立角色特征，保证多张一致" },
      { title: "出片精修", detail: "肤质、发丝与服装细节精修" },
      { title: "交付", detail: "8 张高清成片，含 2 次修改" },
    ],
    orders_count: 268,
    rating: 4.8,
  },
  {
    id: "s3",
    creator_id: "c1",
    title: "品牌 AI 短片 · 15 秒产品叙事",
    category: "品牌 AI 短片",
    usage: ["品牌传播", "广告投放"],
    cover_url: img("svc-3", 900, 1100),
    gallery: [img("svc-3a", 900, 700), img("svc-3b", 900, 700)],
    price_from: 899,
    delivery_days: 5,
    quantity: "15 秒成片",
    revisions: 1,
    commercial_use: true,
    source_files: true,
    media_type: "video",
    description:
      "15 秒品牌短片，含分镜设计、AI 画面生成、剪辑与配乐。适合新品发布、品牌形象与信息流投放。",
    process: [
      { title: "脚本分镜", detail: "根据品牌卖点撰写 15s 脚本" },
      { title: "画面生成", detail: "关键帧生成与动态化" },
      { title: "剪辑合成", detail: "节奏剪辑、调色、配乐" },
      { title: "交付", detail: "1080P / 4K 成片与工程文件" },
    ],
    orders_count: 97,
    rating: 4.9,
  },
  {
    id: "s4",
    creator_id: "c3",
    title: "潮玩 IP 动态短片 · 10 秒循环",
    category: "潮玩 IP 动态",
    usage: ["社交媒体", "广告投放"],
    cover_url: img("svc-4", 900, 1100),
    gallery: [img("svc-4a", 900, 700), img("svc-4b", 900, 700)],
    price_from: 699,
    delivery_days: 4,
    quantity: "10 秒成片",
    revisions: 1,
    commercial_use: true,
    source_files: false,
    media_type: "video",
    description: "把潮玩手办 / IP 形象转成有质感的动态短片，适合新品预热、抽盒活动与社媒投放。",
    process: [
      { title: "形象梳理", detail: "确认 IP 造型与材质" },
      { title: "分镜设计", detail: "10 秒节奏与镜头运动" },
      { title: "动态生成", detail: "关键帧动画与合成" },
      { title: "交付", detail: "竖版 / 横版双尺寸" },
    ],
    orders_count: 143,
    rating: 4.7,
  },
  {
    id: "s5",
    creator_id: "c4",
    title: "品牌主视觉 KV · 单张高完成度",
    category: "海报 / KV",
    usage: ["品牌传播", "线下物料"],
    cover_url: img("svc-5", 900, 1100),
    gallery: [img("svc-5a", 900, 700)],
    price_from: 599,
    delivery_days: 4,
    quantity: "1 张 KV + 2 尺寸适配",
    revisions: 2,
    commercial_use: true,
    source_files: true,
    media_type: "image",
    description: "以品牌调性为核心的主视觉，含画面概念、排版与多尺寸适配，可直接用于线上线下物料。",
    process: [
      { title: "调性拆解", detail: "梳理品牌关键词与参考" },
      { title: "概念提案", detail: "2 个方向草图" },
      { title: "视觉落地", detail: "画面制作与排版" },
      { title: "尺寸适配", detail: "输出多平台尺寸" },
    ],
    orders_count: 86,
    rating: 4.9,
  },
  {
    id: "s6",
    creator_id: "c4",
    title: "空间概念图 · 门店与展陈提案",
    category: "空间与建筑",
    usage: ["内部提案", "品牌传播"],
    cover_url: img("svc-6", 900, 1100),
    gallery: [img("svc-6a", 900, 700)],
    price_from: 799,
    delivery_days: 5,
    quantity: "4 张概念图",
    revisions: 1,
    commercial_use: true,
    source_files: false,
    media_type: "image",
    description: "门店、快闪与展陈空间的 AI 概念图，用于内部提案与招商沟通，可指定材质与色彩体系。",
    process: [
      { title: "空间信息", detail: "平面图与风格参考" },
      { title: "概念生成", detail: "多视角画面" },
      { title: "细化", detail: "材质与灯光调整" },
      { title: "交付", detail: "4 张高清概念图" },
    ],
    orders_count: 54,
    rating: 4.8,
  },
  {
    id: "s7",
    creator_id: "c2",
    title: "电商短视频 · 服饰上身动态",
    category: "电商短视频",
    usage: ["电商详情页", "广告投放"],
    cover_url: img("svc-7", 900, 1100),
    gallery: [img("svc-7a", 900, 700)],
    price_from: 899,
    delivery_days: 6,
    quantity: "20 秒成片",
    revisions: 1,
    commercial_use: true,
    source_files: false,
    media_type: "video",
    description: "服饰类目 AI 上身短视频，模特形象可定制，含面料动态与场景切换。",
    process: [
      { title: "形象与服装", detail: "确认模特与服装素材" },
      { title: "关键帧", detail: "上身视角与动作设计" },
      { title: "动态生成", detail: "面料与光影动态" },
      { title: "交付", detail: "竖版成片" },
    ],
    orders_count: 61,
    rating: 4.7,
  },
  {
    id: "s8",
    creator_id: "c3",
    title: "概念插画 · 世界观与角色设定",
    category: "插画与概念",
    usage: ["内部提案", "社交媒体"],
    cover_url: img("svc-8", 900, 1100),
    gallery: [img("svc-8a", 900, 700)],
    price_from: 459,
    delivery_days: 5,
    quantity: "3 张设定图",
    revisions: 2,
    commercial_use: false,
    source_files: false,
    media_type: "image",
    description: "面向游戏、动画与品牌 IP 的概念设定，包含角色三视图方向与世界观氛围图。",
    process: [
      { title: "设定沟通", detail: "世界观与角色关键词" },
      { title: "草图", detail: "方向草图确认" },
      { title: "精绘", detail: "细节与色彩" },
      { title: "交付", detail: "3 张高清设定图" },
    ],
    orders_count: 39,
    rating: 4.6,
  },
];

export const portfolios: Portfolio[] = [
  { id: "p1", creator_id: "c1", title: "威士忌品牌产品氛围图", cover_url: img("pf-1", 800, 1100), media_type: "image", category: "AI 商品场景图", tags: ["酒水", "质感光影"], likes: 1284, ratio: "tall" },
  { id: "p2", creator_id: "c2", title: "秋冬系列 AI 模特写真", cover_url: img("pf-2", 800, 800), media_type: "image", category: "AI 人物写真", tags: ["服饰", "胶片"], likes: 932, ratio: "square" },
  { id: "p3", creator_id: "c3", title: "潮玩新品 10s 循环动态", cover_url: img("pf-3", 900, 600), media_type: "video", category: "潮玩 IP 动态", tags: ["IP", "动态"], likes: 774, ratio: "wide" },
  { id: "p4", creator_id: "c4", title: "咖啡品牌春季 KV", cover_url: img("pf-4", 800, 1100), media_type: "image", category: "海报 / KV", tags: ["品牌", "排版"], likes: 651, ratio: "tall" },
  { id: "p5", creator_id: "c1", title: "护肤品礼盒场景系列", cover_url: img("pf-5", 800, 800), media_type: "image", category: "AI 商品场景图", tags: ["美妆", "系列一致"], likes: 1102, ratio: "square" },
  { id: "p6", creator_id: "c4", title: "快闪店空间概念", cover_url: img("pf-6", 900, 600), media_type: "image", category: "空间与建筑", tags: ["空间", "展陈"], likes: 488, ratio: "wide" },
  { id: "p7", creator_id: "c2", title: "美妆代言形象大片", cover_url: img("pf-7", 800, 1100), media_type: "image", category: "AI 人物写真", tags: ["美妆", "人物一致性"], likes: 845, ratio: "tall" },
  { id: "p8", creator_id: "c3", title: "国潮 IP 角色设定", cover_url: img("pf-8", 800, 800), media_type: "image", category: "插画与概念", tags: ["IP", "设定"], likes: 512, ratio: "square" },
  { id: "p9", creator_id: "c1", title: "红酒品牌 15s 短片", cover_url: img("pf-9", 900, 600), media_type: "video", category: "品牌 AI 短片", tags: ["酒水", "短片"], likes: 967, ratio: "wide" },
  { id: "p10", creator_id: "c4", title: "家居品牌生活场景", cover_url: img("pf-10", 800, 1100), media_type: "image", category: "AI 商品场景图", tags: ["家居", "自然光"], likes: 436, ratio: "tall" },
  { id: "p11", creator_id: "c2", title: "运动品牌街头系列", cover_url: img("pf-11", 800, 800), media_type: "image", category: "AI 人物写真", tags: ["运动", "街头"], likes: 623, ratio: "square" },
  { id: "p12", creator_id: "c3", title: "盲盒开箱动态短片", cover_url: img("pf-12", 900, 600), media_type: "video", category: "潮玩 IP 动态", tags: ["盲盒", "动态"], likes: 389, ratio: "wide" },
];

export const requests: CreatorRequest[] = [
  {
    id: "r1",
    title: "红酒品牌需要一套 AI 产品图 + 15s 视频",
    owner_name: "黎境酒业",
    owner_avatar: img("own-1", 200, 200),
    owner_kind: "品牌方",
    category: "AI 商品场景图",
    media_type: "mixed",
    description:
      "我们是一个新锐红酒品牌，秋季新品上线需要一套视觉物料。希望画面质感偏暗调、克制、有европ старый庄园氛围，不要过度炫技。产品瓶身结构必须准确，标签文字清晰可读。视频用于小红书与视频号首发。",
    deliverables: ["6 张产品场景图（含 2 张细节图）", "1 条 15 秒竖版短片", "可用于电商与社媒投放"],
    budget_min: 1500,
    budget_max: 2500,
    deadline: "2026-10-08",
    created_at: "2026-09-14",
    status: "recruiting",
    applications_count: 3,
    views: 268,
    attachments: ["产品白底图.zip", "参考情绪板.pdf"],
    requirements: { commercial_use: true, retouch: true, consistency: true, source_files: false },
  },
  {
    id: "r2",
    title: "美妆品牌双十一详情页场景图 12 张",
    owner_name: "朝露实验室",
    owner_avatar: img("own-2", 200, 200),
    owner_kind: "品牌方",
    category: "AI 商品场景图",
    media_type: "image",
    description: "精华与面霜两条线，需要统一的系列感，色调偏清透。用于天猫详情页。",
    deliverables: ["12 张场景图", "统一色调与构图体系"],
    budget_min: 2000,
    budget_max: 3000,
    deadline: "2026-10-02",
    created_at: "2026-09-13",
    status: "recruiting",
    applications_count: 7,
    views: 512,
    attachments: ["产品清单.xlsx"],
    requirements: { commercial_use: true, retouch: true, consistency: true, source_files: true },
  },
  {
    id: "r3",
    title: "潮玩品牌新品预热动态短片",
    owner_name: "MONO 玩造",
    owner_avatar: img("own-3", 200, 200),
    owner_kind: "品牌方",
    category: "潮玩 IP 动态",
    media_type: "video",
    description: "新品盲盒预热，需要 3 条 8-10 秒竖版动态，风格活泼但不廉价。",
    deliverables: ["3 条 10 秒竖版短片"],
    budget_min: 1800,
    budget_max: 2600,
    deadline: "2026-09-30",
    created_at: "2026-09-12",
    status: "matched",
    applications_count: 5,
    views: 341,
    attachments: [],
    requirements: { commercial_use: true, retouch: false, consistency: true, source_files: false },
  },
  {
    id: "r4",
    title: "独立咖啡品牌春季 KV 与门店海报",
    owner_name: "半山咖啡",
    owner_avatar: img("own-4", 200, 200),
    owner_kind: "个人商户",
    category: "海报 / KV",
    media_type: "image",
    description: "需要一张主 KV，延展 3 个尺寸用于门店、外卖平台与社媒。",
    deliverables: ["1 张 KV", "3 个尺寸延展"],
    budget_min: 800,
    budget_max: 1200,
    deadline: "2026-10-12",
    created_at: "2026-09-11",
    status: "recruiting",
    applications_count: 9,
    views: 604,
    attachments: ["品牌 Logo.ai"],
    requirements: { commercial_use: true, retouch: false, consistency: false, source_files: true },
  },
  {
    id: "r5",
    title: "服饰品牌 AI 模特上身图（长期合作）",
    owner_name: "PLAIN 素本",
    owner_avatar: img("own-5", 200, 200),
    owner_kind: "品牌方",
    category: "AI 人物写真",
    media_type: "image",
    description: "每月约 20 款服饰上身图，需要固定模特形象，长期稳定合作。",
    deliverables: ["首批 20 款 × 3 张", "固定模特形象"],
    budget_min: 4000,
    budget_max: 6000,
    deadline: "2026-10-20",
    created_at: "2026-09-10",
    status: "in_progress",
    applications_count: 12,
    views: 887,
    attachments: [],
    requirements: { commercial_use: true, retouch: true, consistency: true, source_files: false },
  },
  {
    id: "r6",
    title: "健康食品品牌社媒素材包",
    owner_name: "谷物纪",
    owner_avatar: img("own-6", 200, 200),
    owner_kind: "品牌方",
    category: "AI 商品场景图",
    media_type: "mixed",
    description: "一个月社媒素材，含 10 张图与 2 条短视频，风格自然、明亮。",
    deliverables: ["10 张图", "2 条 10 秒短片"],
    budget_min: 2500,
    budget_max: 3500,
    deadline: "2026-10-18",
    created_at: "2026-09-09",
    status: "recruiting",
    applications_count: 4,
    views: 233,
    attachments: [],
    requirements: { commercial_use: true, retouch: false, consistency: true, source_files: false },
  },
];

export const applications: Application[] = [
  {
    id: "a1",
    request_id: "r1",
    creator_id: "c1",
    status: "submitted",
    quote: 2200,
    duration_days: 7,
    plan: "先做 2 组暗调方向草图确认氛围，产品瓶身用真实白底图做结构参考，保证标签文字可读。视频部分以「开瓶—倒酒—举杯」三镜完成 15 秒叙事，配乐可提供 2 版选择。",
    cases: [img("case-1", 600, 600), img("case-2", 600, 600), img("case-3", 600, 600)],
    created_at: "2026-09-15",
  },
  {
    id: "a2",
    request_id: "r1",
    creator_id: "c4",
    status: "submitted",
    quote: 1800,
    duration_days: 6,
    plan: "偏品牌视角的处理：先定 KV 级主画面，再延展细节图，短片以静帧运镜为主，成本可控、调性统一。",
    cases: [img("case-4", 600, 600), img("case-5", 600, 600)],
    created_at: "2026-09-15",
  },
  {
    id: "a3",
    request_id: "r1",
    creator_id: "c3",
    status: "submitted",
    quote: 1500,
    duration_days: 9,
    plan: "以动态见长，视频部分可做更复杂的液体流动镜头，图片部分交付 6 张氛围场景。",
    cases: [img("case-6", 600, 600)],
    created_at: "2026-09-16",
  },
];

const today = "2026-09-16";

export const orders: Order[] = [
  {
    id: "o1",
    order_no: "AG20260912001",
    request_id: "r5",
    creator_id: "c2",
    buyer_name: "PLAIN 素本",
    buyer_avatar: img("own-5", 200, 200),
    title: "服饰品牌 AI 模特上身图 · 首批 20 款",
    status: "pending_review",
    amount: 5200,
    scope: "20 款 × 3 张上身图，固定模特形象，含平台尺寸适配",
    revisions_total: 2,
    revisions_used: 0,
    deadline: "2026-09-20",
    commercial_use: true,
    source_files: false,
    created_at: "2026-09-12",
    deliveries: [
      {
        id: "d1",
        order_id: "o1",
        version: 1,
        note: "第一批 8 款上身图，模特形象已固定，等待确认色调方向。",
        files: [
          { name: "look_01.jpg", thumb: img("del-1", 400, 500) },
          { name: "look_02.jpg", thumb: img("del-2", 400, 500) },
          { name: "look_03.jpg", thumb: img("del-3", 400, 500) },
        ],
        created_at: "2026-09-14 16:20",
      },
      {
        id: "d2",
        order_id: "o1",
        version: 2,
        note: "补齐剩余 12 款，统一提亮 0.3EV，袖口褶皱已修正。",
        files: [
          { name: "look_09.jpg", thumb: img("del-4", 400, 500) },
          { name: "look_10.jpg", thumb: img("del-5", 400, 500) },
          { name: "look_11.jpg", thumb: img("del-6", 400, 500) },
          { name: "全部成片.zip", thumb: img("del-7", 400, 500) },
        ],
        created_at: "2026-09-16 10:05",
      },
    ],
    messages: [
      { id: "m1", order_id: "o1", author: "system", author_name: "系统", content: "订单已创建，成交金额 ¥5,200，交付期限 2026-09-20，包含 2 次修改。", created_at: "09-12 09:30" },
      { id: "m2", order_id: "o1", author: "creator", author_name: "林山 Linshan", content: "已收到素材，今天先做模特形象定版，明天出第一批。", created_at: "09-12 10:12" },
      { id: "m3", order_id: "o1", author: "buyer", author_name: "PLAIN 素本", content: "好的，模特气质希望偏干净、日常一点。", created_at: "09-12 10:40" },
      { id: "m4", order_id: "o1", author: "creator", author_name: "林山 Linshan", content: "第一批 8 款已提交，见 V1。", created_at: "09-14 16:21" },
      { id: "m5", order_id: "o1", author: "buyer", author_name: "PLAIN 素本", content: "整体可以，略暗，能不能整体提亮一点。", created_at: "09-15 09:02" },
      { id: "m6", order_id: "o1", author: "creator", author_name: "林山 Linshan", content: "已提亮并补齐全部 20 款，V2 请验收。", created_at: "09-16 10:06" },
    ],
  },
  {
    id: "o2",
    order_no: "AG20260908004",
    service_id: "s1",
    creator_id: "c1",
    buyer_name: "谷物纪",
    buyer_avatar: img("own-6", 200, 200),
    title: "AI 商品场景图 · 电商主图与详情页整套",
    status: "in_progress",
    amount: 299,
    scope: "5 张成片，含主图 1 张、场景图 3 张、细节图 1 张",
    revisions_total: 1,
    revisions_used: 0,
    deadline: "2026-09-18",
    commercial_use: true,
    source_files: true,
    created_at: "2026-09-15",
    deliveries: [],
    messages: [
      { id: "m7", order_id: "o2", author: "system", author_name: "系统", content: "订单已创建，成交金额 ¥299。", created_at: "09-15 14:00" },
      { id: "m8", order_id: "o2", author: "creator", author_name: "Mori AI Studio", content: "已开始制作，预计 09-17 提交第一版。", created_at: "09-15 15:22" },
    ],
  },
  {
    id: "o3",
    order_no: "AG20260901002",
    service_id: "s4",
    creator_id: "c3",
    buyer_name: "MONO 玩造",
    buyer_avatar: img("own-3", 200, 200),
    title: "潮玩 IP 动态短片 · 10 秒循环",
    status: "completed",
    amount: 699,
    scope: "10 秒竖版 + 横版成片",
    revisions_total: 1,
    revisions_used: 1,
    deadline: "2026-09-05",
    commercial_use: true,
    source_files: false,
    created_at: "2026-09-01",
    deliveries: [
      { id: "d3", order_id: "o3", version: 1, note: "初版动态", files: [{ name: "v1.mp4", thumb: img("del-8", 400, 500) }], created_at: "09-03 18:00" },
      { id: "d4", order_id: "o3", version: 2, note: "按要求放慢结尾节奏", files: [{ name: "final.mp4", thumb: img("del-9", 400, 500) }], created_at: "09-05 11:30" },
    ],
    messages: [
      { id: "m9", order_id: "o3", author: "system", author_name: "系统", content: "订单已完成。", created_at: "09-05 12:00" },
    ],
  },
];

export const reviews: Review[] = [
  { id: "rv1", creator_id: "c1", order_id: "o2", author_name: "黎境酒业", author_avatar: img("own-1", 200, 200), rating: 5, content: "产品结构还原非常准，标签文字没有糊，沟通效率也高，第二次合作了。", tags: ["还原准确", "沟通顺畅", "按时交付"], created_at: "2026-09-08" },
  { id: "rv2", creator_id: "c1", order_id: "o2", author_name: "谷物纪", author_avatar: img("own-6", 200, 200), rating: 5, content: "风格提案阶段就给了三组方向，省了很多来回。", tags: ["方案清晰"], created_at: "2026-08-29" },
  { id: "rv3", creator_id: "c1", order_id: "o2", author_name: "朝露实验室", author_avatar: img("own-2", 200, 200), rating: 4.5, content: "整体满意，细节图稍微多改了一轮。", tags: ["质量稳定"], created_at: "2026-08-20" },
  { id: "rv4", creator_id: "c2", order_id: "o1", author_name: "PLAIN 素本", author_avatar: img("own-5", 200, 200), rating: 5, content: "模特一致性处理得很好，长期合作稳定。", tags: ["人物一致性", "响应快"], created_at: "2026-09-16" },
  { id: "rv5", creator_id: "c3", order_id: "o3", author_name: "MONO 玩造", author_avatar: img("own-3", 200, 200), rating: 5, content: "动态节奏很有感觉，改一轮就定稿。", tags: ["有创意"], created_at: "2026-09-05" },
];

export const currentUser = {
  id: "u1",
  name: "Mori AI Studio",
  avatar_url: img("mori-avatar", 300, 300),
  creator_id: "c1",
};

export const getCreator = (id: string) => creators.find((c) => c.id === id);
export const getCreatorByHandle = (handle: string) => creators.find((c) => c.handle === handle);
export const getService = (id: string) => services.find((s) => s.id === id);
export const getRequest = (id: string) => requests.find((r) => r.id === id);
export const getOrder = (id: string) => orders.find((o) => o.id === id);
export const servicesByCreator = (id: string) => services.filter((s) => s.creator_id === id);
export const portfoliosByCreator = (id: string) => portfolios.filter((p) => p.creator_id === id);
export const reviewsByCreator = (id: string) => reviews.filter((r) => r.creator_id === id);
export const applicationsByRequest = (id: string) =>
  applications.filter((a) => a.request_id === id);

export const TODAY = today;
export const formatCNY = (n: number) => `¥${n.toLocaleString("zh-CN")}`;